<?php 
require_once 'db.php'; require_once 'dil.php';
$conn = new mysqli($hn, $un, $pw, $db);
if (!isset($_SESSION['user_id']) || !isset($_SESSION['is_admin']) || $_SESSION['is_admin'] != 1) { header("Location: index.php"); exit; }
if (isset($_GET['action']) && $_GET['action'] == 'logout') { session_destroy(); header("Location: index.php"); exit; }
if (isset($_FILES['site_logo']) && $_FILES['site_logo']['error'] == 0) { $target_file = "logo.png"; $check = getimagesize($_FILES["site_logo"]["tmp_name"]); if($check !== false) { if (move_uploaded_file($_FILES["site_logo"]["tmp_name"], $target_file)) { header("Location: admin.php?msg=logo_updated"); } } }
if (isset($_POST['delete_user'])) { $uid = $conn->real_escape_string($_POST['user_id']); $conn->query("DELETE FROM votes_history WHERE user_id='$uid'"); $polls = $conn->query("SELECT id FROM polls WHERE created_by='$uid'"); while($p = $polls->fetch_assoc()) { $pid = $p['id']; $imgs = $conn->query("SELECT image_path FROM options WHERE poll_id='$pid'"); while($r = $imgs->fetch_assoc()){ if($r['image_path'] && file_exists($r['image_path'])) unlink($r['image_path']); } $conn->query("DELETE FROM options WHERE poll_id='$pid'"); $conn->query("DELETE FROM votes_history WHERE poll_id='$pid'"); $conn->query("DELETE FROM polls WHERE id='$pid'"); } $conn->query("DELETE FROM users WHERE id='$uid'"); header("Location: admin.php"); }
if (isset($_POST['delete_poll'])) { $pid = $conn->real_escape_string($_POST['poll_id']); $imgs = $conn->query("SELECT image_path FROM options WHERE poll_id='$pid'"); while($r = $imgs->fetch_assoc()){ if($r['image_path'] && file_exists($r['image_path'])) unlink($r['image_path']); } $conn->query("DELETE FROM votes_history WHERE poll_id='$pid'"); $conn->query("DELETE FROM options WHERE poll_id='$pid'"); $conn->query("DELETE FROM polls WHERE id='$pid'"); header("Location: admin.php"); }
?>
<!DOCTYPE html>
<html lang="<?php echo $lang_code; ?>">
<head><meta charset="UTF-8"><title>Admin</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="style.css"></head>
<body id="mainBody">
<div class="fixed-btn-left"><a href="index.php" class="fixed-toggle" title="<?php echo $l['home_btn']; ?>">🏠</a></div>
<div class="fixed-btn-right"><button class="fixed-toggle" onclick="toggleDarkMode()" id="modeBtn">🌙</button><a href="?lang=<?php echo $lang_code == 'tr' ? 'en' : 'tr'; ?>" class="fixed-toggle"><?php echo $lang_code == 'tr' ? 'EN' : 'TR'; ?></a></div>
<div class="container">
    <div class="navbar"><a href="index.php" class="brand"><img src="logo.png?v=<?php echo time(); ?>" alt="Logo" class="logo-img" onerror="this.style.display='none'">Admin<span style="color:var(--accent-color)">Panel</span></a><div class="d-flex gap-10 align-center"><a href="?action=logout" class="btn btn-danger"><?php echo $l['logout']; ?></a></div></div>
    <h3 class="section-title mt-40">⚙️ Site Ayarları</h3>
    <div class="card d-flex gap-20 align-center"><img src="logo.png?v=<?php echo time(); ?>" class="admin-logo-preview"><form method="post" enctype="multipart/form-data" class="d-flex gap-10 align-center"><input type="file" name="site_logo" required accept="image/*"><button type="submit" class="btn btn-primary">Güncelle</button></form></div>
    <h3 class="section-title mt-40">👥 <?php echo $l['user_mgmt']; ?></h3>
    <div class="table-container"><table><thead><tr><th>ID</th><th><?php echo $l['name']; ?></th><th><?php echo $l['email']; ?></th><th><?php echo $l['role']; ?></th><th class="text-left"><?php echo $l['action']; ?></th></tr></thead><tbody><?php $users = $conn->query("SELECT * FROM users ORDER BY id DESC"); while($u = $users->fetch_assoc()): ?><tr><td>#<?php echo $u['id']; ?></td><td><?php echo $u['name'] . " " . $u['surname']; ?></td><td><?php echo $u['email']; ?></td><td><?php if($u['is_admin']): ?><span class="role-badge"><?php echo $l['admin']; ?></span><?php else: ?><span style="color:var(--text-secondary)"><?php echo $l['member']; ?></span><?php endif; ?></td><td class="text-left"><?php if(!$u['is_admin'] || $u['id'] != $_SESSION['user_id']): ?><form method="post" onsubmit="return confirm('<?php echo $l['del_confirm_user']; ?>')"><input type="hidden" name="user_id" value="<?php echo $u['id']; ?>"><button type="submit" name="delete_user" class="btn btn-danger" style="padding:5px 12px; font-size:0.8rem;">🗑️ <?php echo $l['delete']; ?></button></form><?php endif; ?></td></tr><?php endwhile; ?></tbody></table></div>
    <h3 class="section-title mt-40">📊 <?php echo $l['poll_mgmt']; ?></h3>
    <div class="table-container"><table><thead><tr><th>ID</th><th><?php echo $l['poll_question']; ?></th><th>Oluşturan</th><th>Oy</th><th class="text-left"><?php echo $l['action']; ?></th></tr></thead><tbody><?php $polls = $conn->query("SELECT p.*, (SELECT COUNT(*) FROM votes_history WHERE poll_id=p.id) as votes FROM polls p ORDER BY p.id DESC"); while($p = $polls->fetch_assoc()): $creator = $p['is_anonymous'] ? $l['anonymous'] : $p['creator_name']; ?><tr><td>#<?php echo $p['id']; ?></td><td style="font-weight:600;"><?php echo $p['question']; ?></td><td><?php echo $creator; ?></td><td><?php echo $p['votes']; ?> / <?php echo $p['quota']; ?></td><td class="text-left"><form method="post" onsubmit="return confirm('<?php echo $l['del_confirm_poll']; ?>')"><input type="hidden" name="poll_id" value="<?php echo $p['id']; ?>"><button type="submit" name="delete_poll" class="btn btn-danger" style="padding:5px 12px; font-size:0.8rem;">🗑️ <?php echo $l['delete']; ?></button></form></td></tr><?php endwhile; ?></tbody></table></div>
</div>
<script>
function toggleDarkMode() { const body = document.body; const btn = document.getElementById('modeBtn'); body.classList.toggle('dark-mode'); if (body.classList.contains('dark-mode')) { localStorage.setItem('theme', 'dark'); if(btn) btn.innerHTML = "☀️"; } else { localStorage.setItem('theme', 'light'); if(btn) btn.innerHTML = "🌙"; } }
window.onload = function() { if (localStorage.getItem('theme') === 'dark') { document.body.classList.add('dark-mode'); const btn = document.getElementById('modeBtn'); if(btn) btn.innerHTML = "☀️"; } }
</script>
</body>
</html>